name: CI - Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B -DskipTests=false clean package

      - name: Upload shaded jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: society-maintenance-app-jar
          path: target/society-maintenance-app-1.0-SNAPSHOT.jar
